### PR TITLE
Minor visual tweaks

### PR DESCRIPTION
**Pull request by foresmac**
- Make the type slightly larger
- Give the badge a larger chamfer radius
- Verdana seems to look better than default Helvetica, maybe because
  most badges use Verdana?

@jrit Thoughts?

### CODE REVIEW

**Comment by foresmac** [comment]
Here's an update sample:
screen shot 2015-08-27 at 5 36 07 pm

**Comment by jrit** [comment]
I don't want to change the defaults because they match what is most commonly used online, but I'm totally open to making things more customizable through adding some options.

**Comment by foresmac** [comment]
Yeah, I think it's easy to make those tweaks options.

On another tangent: I was goofing around last night and came up with this sweet drop shadow; thoughts?

``` xml
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="20">
<defs>
    <filter id="drop-shadow">
      <feOffset result="offOut" in="SourceAlpha" dx="0.5" dy="1" />
      <feGaussianBlur result="blurOut" in="offOut" stdDeviation="0.5" />
      <feBlend in="SourceGraphic" in2="blurOut" mode="normal" />
    </filter>
  </defs>
    <mask id="a"><rect width="100" height="20" rx="5" ry="5" fill="#fff"/></mask>
    <g mask="url(#a)">
        <path fill="#555" d="M0 0h60v20H0z"/>
        <path fill="#4b1" d="M60 0h60v20H60z"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="Verdana, sans-serif" font-size="12">
        <text x="30" y="14" filter="url(#drop-shadow)">line cvr</text>
        <text x="80" y="14" filter="url(#drop-shadow)">98%</text>
    </g>
</svg>
```

Sample:
screen shot 2015-08-28 at 2 54 11 am

**Comment by jrit** [comment]
Drop shadow looks good, I have two thoughts about it
- Is it compatible everywhere? I think probably yes, but my quick research doesn't say one way or the other.
- Does it look better than the other method at all sizes since it sounds like you are going to add a scaling option?

**Comment by foresmac** [comment]
1. I think our only concern might be that it's not compatible with IE < 10:
   http://www.w3schools.com/svg/svg_filters_intro.asp
2. I'm actually adding a hard limit of 17 on the type size, here's a sample with that (and I didn't scale the width at all because I was trying to be quick): 
   screen shot 2015-08-28 at 10 11 48 am

**Comment by foresmac** [comment]
If you're ok with the caveats I noted above, I'll open a separate PR for the drop shadow. Otherwise I think this is good to go with the suggestions you made earlier.

**Comment by jrit** [comment]
I mistakenly thought the height of the badge was changing because the PNGs posted above must be saved at 2x or something, but I guess you just have it so the font size can go up to 17 so that it won't get cut off with the fixed height of 20. LGTM.

**Pull request merged**
